/**
 * Signal Thresholds Configuration
 *
 * Centralized threshold values for climate signal detection in Layer2.
 * Modify this file to adjust sensitivity without changing detection logic.
 *
 * Each threshold key corresponds to a parameter used in detectSignalsV2().
 * Null means the threshold does not apply for that region.
 */

export const REGION_THRESHOLDS = {
  costa: {
    extreme_heat_delta_short: 15,
    extreme_heat_delta_mid:   25,
    extreme_heat_delta_long:  35,
    tropical_nights_delta_short: 15,
    tropical_nights_delta_mid:   25,
    tropical_nights_delta_long:  35,
    temp_increase_short: 1.5,
    temp_increase_mid:   2.5,
    temp_increase_long:  3.5,
    drought_pr_pct: -30,
    drought_pr_pct_long: -40,
    extreme_rain_rx5day_pct: 25,
    extreme_rain_rx1day_mm: 50,
    extreme_rain_rx1day_mm_long: 60,
    drought_cdd_delta: 10,
    r50mm_delta: 5,
    severe_heat_delta: 5,
    moderate_heat_delta: 20,
    r20mm_delta: 5,
    tx84rr_delta_pct: 10,
    tasmax_threshold_c: 35,
    prectot_drought_mm: 0.5,
  },
  sierra: {
    extreme_heat_delta_short: 5,
    extreme_heat_delta_mid:   10,
    extreme_heat_delta_long:  15,
    tropical_nights_delta_short: null,
    tropical_nights_delta_mid:   null,
    tropical_nights_delta_long:  null,
    temp_increase_short: 1.0,
    temp_increase_mid:   2.0,
    temp_increase_long:  3.0,
    drought_pr_pct: -15,
    drought_pr_pct_long: -25,
    extreme_rain_rx5day_pct: 15,
    extreme_rain_rx1day_mm: 40,
    extreme_rain_rx1day_mm_long: 50,
    drought_cdd_delta: 5,
    r50mm_delta: 3,
    severe_heat_delta: null,
    moderate_heat_delta: 15,
    r20mm_delta: 3,
    tx84rr_delta_pct: 8,
    tasmax_threshold_c: 30,
    prectot_drought_mm: 0.5,
  },
  puna: {
    extreme_heat_delta_short: null,
    extreme_heat_delta_mid:   null,
    extreme_heat_delta_long:  null,
    tropical_nights_delta_short: null,
    tropical_nights_delta_mid:   null,
    tropical_nights_delta_long:  null,
    temp_increase_short: 0.8,
    temp_increase_mid:   1.5,
    temp_increase_long:  2.5,
    drought_pr_pct: -20,
    drought_pr_pct_long: -30,
    extreme_rain_rx5day_pct: 15,
    extreme_rain_rx1day_mm: 30,
    extreme_rain_rx1day_mm_long: 40,
    drought_cdd_delta: 5,
    r50mm_delta: 3,
    severe_heat_delta: null,
    moderate_heat_delta: 10,
    r20mm_delta: 3,
    tx84rr_delta_pct: 8,
    tasmax_threshold_c: 30,
    prectot_drought_mm: 0.5,
  },
  default: {
    extreme_heat_delta_short: 10,
    extreme_heat_delta_mid:   20,
    extreme_heat_delta_long:  30,
    tropical_nights_delta_short: 10,
    tropical_nights_delta_mid:   20,
    tropical_nights_delta_long:  30,
    temp_increase_short: 1.5,
    temp_increase_mid:   2.5,
    temp_increase_long:  3.5,
    drought_pr_pct: -15,
    drought_pr_pct_long: -30,
    extreme_rain_rx5day_pct: 20,
    extreme_rain_rx1day_mm: 50,
    extreme_rain_rx1day_mm_long: 60,
    drought_cdd_delta: 15,
    drought_cdd_delta_long: 20,
    r50mm_delta: 5,
    severe_heat_delta: 3,
    moderate_heat_delta: 15,
    r20mm_delta: 5,
    tx84rr_delta_pct: 10,
    tasmax_threshold_c: 35,
    prectot_drought_mm: 0.5,
  },
};

export const GRI_SCORE_PROB = { bajo: 0.15, medio: 0.50, alto: 0.85 };
