/**
 * businessProfiles.js — Catálogo de perfiles de unidad de negocio.
 *
 * Cada perfil contiene metadata pública para que el motor de riesgos
 * genere impactos coherentes con el giro específico de cada negocio,
 * en lugar de usar sectores genéricos.
 */

const BUSINESS_PROFILES = {
  // ─── Plataforma Financiera ────────────────────────────────────────────────
  interbank: {
    id: "interbank",
    rubro_especifico: "banca múltiple",
    plataforma: "financiera",
    sector_actual: "otros",
    taxonomia_operativa: "banco",
    locales_count: 120,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: true,
    tiene_generador: true,
    estacionamientos_subterraneos: true,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["masivo", "empresas"],
    productos_clave: ["cuentas", "tarjetas", "creditos", "seguros"],
    proveedores_criticos: ["ti", "energia"],
    infraestructura_predominante: "oficina",
    seguro_desastres: true,
    historial_cierres_climaticos: [],
  },
  inteligo: {
    id: "inteligo",
    rubro_especifico: "wealth management y corretaje",
    plataforma: "financiera",
    sector_actual: "otros",
    taxonomia_operativa: "banco_inversiones",
    locales_count: 3,
    presencia_geografica: ["lima", "internacional"],
    tiene_cadena_frio: false,
    tiene_data_center: true,
    tiene_generador: true,
    estacionamientos_subterraneos: true,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["alto_patrimonio", "empresas"],
    productos_clave: ["wealth_management", "corretaje", "fondos_mutuos", "asesoria_financiera"],
    proveedores_criticos: ["ti", "proveedores_datos_financieros"],
    infraestructura_predominante: "oficina",
    seguro_desastres: true,
    historial_cierres_climaticos: [],
  },
  izipay: {
    id: "izipay",
    rubro_especifico: "procesadora de pagos y adquirencia",
    plataforma: "financiera",
    sector_actual: "otros",
    taxonomia_operativa: "procesadora_pagos",
    locales_count: 5,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: true,
    tiene_generador: true,
    estacionamientos_subterraneos: true,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["masivo", "empresas"],
    productos_clave: ["pos", "pasarela_pagos", "link_pago", "app_cobro"],
    proveedores_criticos: ["ti", "redes_telecomunicaciones", "fabricantes_pos"],
    infraestructura_predominante: "oficina",
    seguro_desastres: true,
    historial_cierres_climaticos: [],
  },
  interseguro: {
    id: "interseguro",
    rubro_especifico: "seguros generales y de vida",
    plataforma: "financiera",
    sector_actual: "otros",
    taxonomia_operativa: "seguros",
    locales_count: 25,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: false,
    tiene_generador: false,
    estacionamientos_subterraneos: false,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["masivo", "empresas"],
    productos_clave: ["vida", "vehicular", "catastrofico", "salud"],
    proveedores_criticos: ["ti"],
    infraestructura_predominante: "oficina",
    seguro_desastres: false,
    historial_cierres_climaticos: [],
  },
  infinance_xp: {
    id: "infinance_xp",
    rubro_especifico: "financiamiento de consumo y tarjetas de crédito",
    plataforma: "retail",
    sector_actual: "otros",
    taxonomia_operativa: "financiera",
    locales_count: 50,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: false,
    tiene_generador: false,
    estacionamientos_subterraneos: false,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["masivo"],
    productos_clave: ["tarjeta_de_credito", "prestamos_efectivo", "seguros"],
    proveedores_criticos: ["ti", "procesadoras_pago"],
    infraestructura_predominante: "modulo_atencion",
    seguro_desastres: false,
    historial_cierres_climaticos: [],
  },

  // ─── Plataforma Retail ────────────────────────────────────────────────────
  spsa: {
    id: "spsa",
    rubro_especifico: "supermercado y retail de alimentos",
    plataforma: "retail",
    sector_actual: "retail",
    taxonomia_operativa: "supermercado",
    locales_count: 1200,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: true,
    tiene_data_center: true,
    tiene_generador: true,
    estacionamientos_subterraneos: true,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["masivo", "empresas"],
    productos_clave: ["abarrotes", "frescos", "electro", "textil", "bazar"],
    proveedores_criticos: ["alimentos", "logistica", "energia"],
    infraestructura_predominante: "local_comercial",
    seguro_desastres: true,
    historial_cierres_climaticos: [
      "2017: cierres preventivos por niño costero en el norte",
      "2023: afectacion ciclon yaku locales norte",
    ],
  },
  farmacias_peruanas: {
    id: "farmacias_peruanas",
    rubro_especifico: "cadena de farmacias",
    plataforma: "retail",
    sector_actual: "retail",
    taxonomia_operativa: "farmacia",
    locales_count: 2000,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: true,
    tiene_data_center: false,
    tiene_generador: true,
    estacionamientos_subterraneos: false,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["masivo"],
    productos_clave: ["medicamentos", "cuidado_personal", "belleza", "nutricion"],
    proveedores_criticos: ["laboratorios_farmaceuticos", "distribuidores", "logistica"],
    infraestructura_predominante: "local_comercial",
    seguro_desastres: true,
    historial_cierres_climaticos: [
      "2017: afectacion por niño costero",
      "2023: suspension de atencion parcial ciclon yaku",
    ],
  },
  oechsle: {
    id: "oechsle",
    rubro_especifico: "tienda por departamentos",
    plataforma: "retail",
    sector_actual: "retail",
    taxonomia_operativa: "tienda_departamentos",
    locales_count: 25,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: false,
    tiene_generador: true,
    estacionamientos_subterraneos: true,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["masivo"],
    productos_clave: ["moda", "calzado", "electro", "deco", "deportes"],
    proveedores_criticos: ["textileras", "marcas_electrodomesticos", "logistica_importacion"],
    infraestructura_predominante: "local_comercial",
    seguro_desastres: true,
    historial_cierres_climaticos: [],
  },
  real_plaza: {
    id: "real_plaza",
    rubro_especifico: "operador de centros comerciales",
    plataforma: "retail",
    sector_actual: "retail",
    taxonomia_operativa: "centro_comercial",
    locales_count: 21,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: false,
    tiene_generador: true,
    estacionamientos_subterraneos: true,
    depende_turismo: false,
    depende_eventos_presenciales: true,
    clientes: ["masivo", "empresas"],
    productos_clave: ["arrendamiento_locales", "publicidad", "estacionamiento", "eventos"],
    proveedores_criticos: ["limpieza", "seguridad", "energia", "mantenimiento"],
    infraestructura_predominante: "centro_comercial",
    seguro_desastres: true,
    historial_cierres_climaticos: [
      "2017: niño costero piura",
      "2023: prevencion lluvias norte",
    ],
  },
  promart: {
    id: "promart",
    rubro_especifico: "mejoramiento del hogar y construcción",
    plataforma: "retail",
    sector_actual: "retail",
    taxonomia_operativa: "homecenter",
    locales_count: 35,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: false,
    tiene_generador: true,
    estacionamientos_subterraneos: true,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["masivo", "empresas"],
    productos_clave: ["materiales_construccion", "herramientas", "muebles", "decoracion", "iluminacion"],
    proveedores_criticos: ["materiales_construccion", "logistica_importacion", "marcas_herramientas"],
    infraestructura_predominante: "almacen_retail",
    seguro_desastres: true,
    historial_cierres_climaticos: [
      "2017: cierres preventivos norte niño costero",
    ],
  },

  // ─── Plataforma Educación ─────────────────────────────────────────────────
  innova_schools: {
    id: "innova_schools",
    rubro_especifico: "educación básica regular",
    plataforma: "educacion",
    sector_actual: "educacion",
    taxonomia_operativa: "colegio",
    locales_count: 65,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: false,
    tiene_generador: false,
    estacionamientos_subterraneos: false,
    depende_turismo: false,
    depende_eventos_presenciales: true,
    clientes: ["masivo"],
    productos_clave: ["educacion_primaria", "educacion_secundaria", "educacion_inicial", "talleres_extracurriculares"],
    proveedores_criticos: ["material_educativo", "tecnologia_aulas", "servicios_limpieza"],
    infraestructura_predominante: "colegio",
    seguro_desastres: true,
    historial_cierres_climaticos: [
      "2017: suspension clases niño costero",
      "2023: suspension parcial ciclon yaku",
    ],
  },
  utp: {
    id: "utp",
    rubro_especifico: "educación superior universitaria",
    plataforma: "educacion",
    sector_actual: "educacion",
    taxonomia_operativa: "universidad",
    locales_count: 12,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: true,
    tiene_generador: true,
    estacionamientos_subterraneos: true,
    depende_turismo: false,
    depende_eventos_presenciales: true,
    clientes: ["masivo"],
    productos_clave: ["pregrado", "posgrado", "carreras_para_gente_que_trabaja", "cursos_extension"],
    proveedores_criticos: ["plataformas_educativas_ti", "equipamiento_laboratorios"],
    infraestructura_predominante: "universidad",
    seguro_desastres: true,
    historial_cierres_climaticos: [],
  },
  inlearning: {
    id: "inlearning",
    rubro_especifico: "educación técnica y superior",
    plataforma: "educacion",
    sector_actual: "educacion",
    taxonomia_operativa: "instituto",
    locales_count: 20,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: false,
    tiene_generador: false,
    estacionamientos_subterraneos: false,
    depende_turismo: false,
    depende_eventos_presenciales: true,
    clientes: ["masivo"],
    productos_clave: ["carreras_tecnicas", "diplomados", "cursos_cortos"],
    proveedores_criticos: ["tecnologia_educativa", "infraestructura_ti"],
    infraestructura_predominante: "instituto",
    seguro_desastres: true,
    historial_cierres_climaticos: [],
  },

  // ─── Plataforma Entretenimiento y Hospitalidad ────────────────────────────
  la_tinka: {
    id: "la_tinka",
    rubro_especifico: "loterías y apuestas deportivas",
    plataforma: "entretenimiento",
    sector_actual: "entretenimiento",
    taxonomia_operativa: "juegos_azar",
    locales_count: 5000,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: true,
    tiene_generador: true,
    estacionamientos_subterraneos: false,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["masivo"],
    productos_clave: ["tinka", "te_apuesto", "kabal", "ganadiario", "kinelo"],
    proveedores_criticos: ["servidores_transaccionales", "telecomunicaciones", "impresion_boletos"],
    infraestructura_predominante: "modulo_atencion",
    seguro_desastres: false,
    historial_cierres_climaticos: [],
  },
  ngr: {
    id: "ngr",
    rubro_especifico: "cadena de restaurantes y franquicias",
    plataforma: "entretenimiento",
    sector_actual: "restaurantes",
    taxonomia_operativa: "restaurante",
    locales_count: 300,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: true,
    tiene_data_center: false,
    tiene_generador: true,
    estacionamientos_subterraneos: false,
    depende_turismo: false,
    depende_eventos_presenciales: true,
    clientes: ["masivo"],
    productos_clave: ["comida_rapida", "pollos_a_la_brasa", "donuts", "pizza", "chifa"],
    proveedores_criticos: ["alimentos_frescos", "logistica_frio", "embalajes"],
    infraestructura_predominante: "restaurante",
    seguro_desastres: true,
    historial_cierres_climaticos: [
      "2017: interrupcion cadena suministros niño costero",
      "2023: afectacion ciclon yaku locales norte",
    ],
  },
  casa_andina: {
    id: "casa_andina",
    rubro_especifico: "hotelería y turismo",
    plataforma: "entretenimiento",
    sector_actual: "entretenimiento",
    taxonomia_operativa: "hotel",
    locales_count: 18,
    presencia_geografica: ["lima", "cusco", "arequipa", "cajamarca", "nazca"],
    tiene_cadena_frio: true,
    tiene_data_center: false,
    tiene_generador: true,
    estacionamientos_subterraneos: false,
    depende_turismo: true,
    depende_eventos_presenciales: false,
    clientes: ["masivo", "empresas"],
    productos_clave: ["hospedaje", "alimentos", "eventos", "turismo_aventura"],
    proveedores_criticos: ["alimentos", "turismo_operadores"],
    infraestructura_predominante: "hotel",
    seguro_desastres: true,
    historial_cierres_climaticos: [
      "2017: cierre 3 dias por lluvias cusco",
    ],
  },
  cineplanet: {
    id: "cineplanet",
    rubro_especifico: "exhibición cinematográfica",
    plataforma: "entretenimiento",
    sector_actual: "entretenimiento",
    taxonomia_operativa: "cine",
    locales_count: 45,
    presencia_geografica: ["lima", "provincias"],
    tiene_cadena_frio: false,
    tiene_data_center: false,
    tiene_generador: true,
    estacionamientos_subterraneos: true,
    depende_turismo: false,
    depende_eventos_presenciales: true,
    clientes: ["masivo"],
    productos_clave: ["entradas", "dulceria", "publicidad"],
    proveedores_criticos: ["alimentos", "mantenimiento_hvac"],
    infraestructura_predominante: "local_comercial",
    seguro_desastres: false,
    historial_cierres_climaticos: [],
  },

  // ─── Plataforma Salud ─────────────────────────────────────────────────────
  clinica_aviva: {
    id: "clinica_aviva",
    rubro_especifico: "servicios de salud y atención médica",
    plataforma: "salud",
    sector_actual: "salud",
    taxonomia_operativa: "hospital",
    locales_count: 1,
    presencia_geografica: ["lima"],
    tiene_cadena_frio: true,
    tiene_data_center: true,
    tiene_generador: true,
    estacionamientos_subterraneos: true,
    depende_turismo: false,
    depende_eventos_presenciales: true,
    clientes: ["masivo"],
    productos_clave: ["consultas_externas", "emergencia", "maternidad", "cirugia", "laboratorio"],
    proveedores_criticos: ["gases_medicinales", "insumos_medicos", "energia"],
    infraestructura_predominante: "hospital",
    seguro_desastres: true,
    historial_cierres_climaticos: [],
  },
  smi: {
    id: "smi",
    rubro_especifico: "fabricación de envases PET y reciclaje",
    plataforma: "ninguna",
    sector_actual: "industrial",
    taxonomia_operativa: "planta_industrial",
    locales_count: 12,
    presencia_geografica: ["lima", "provincias", "internacional"],
    tiene_cadena_frio: false,
    tiene_data_center: false,
    tiene_generador: true,
    estacionamientos_subterraneos: false,
    depende_turismo: false,
    depende_eventos_presenciales: false,
    clientes: ["empresas"],
    productos_clave: ["preformas_pet", "botellas_pet", "tapas_plasticas", "resina_reciclada"],
    proveedores_criticos: ["resina_pet", "energia_electrica", "aditivos"],
    infraestructura_predominante: "planta_industrial",
    seguro_desastres: true,
    historial_cierres_climaticos: [
      "2017: restricciones logisticas por niño costero",
    ],
  },
};

/**
 * Retorna el perfil completo de una unidad de negocio.
 * @param {string} id - Identificador único (ej. "spsa", "interbank")
 * @returns {object|null} Perfil o null si no existe
 */
export function getBusinessProfile(id) {
  if (!id || typeof id !== 'string') return null;
  const key = id.toLowerCase().trim();
  return BUSINESS_PROFILES[key] ?? null;
}

/**
 * Retorna la taxonomía operativa para una unidad de negocio.
 * Hace override del sector genérico con el rubro específico.
 * @param {string} id
 * @returns {{ taxonomia: string|null, sector: string, profile: object|null }}
 */
export function resolveBusinessTaxonomy(id) {
  const profile = getBusinessProfile(id);
  if (!profile) return { taxonomia: null, sector: null, profile: null };
  return {
    taxonomia: profile.taxonomia_operativa,
    sector: profile.sector_actual,
    profile,
  };
}

/**
 * Lista todas las unidades de negocio disponibles (para frontend).
 * @returns {Array<{ id: string, label: string, plataforma: string, taxonomia: string }>}
 */
export function listBusinessUnits() {
  return Object.values(BUSINESS_PROFILES).map(p => ({
    id: p.id,
    label: p.rubro_especifico,
    nombre: p.id.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
    plataforma: p.plataforma,
    taxonomia: p.taxonomia_operativa,
  }));
}
